name = "the-baseline"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BASELINE_KV"
id = "e1205ab580814cab87a3a86010654195"

[triggers]
crons = ["*/20 * * * *"]
